name: Python Lint (tc-backend com Pylint)

on:
  pull_request:
    paths:
      - 'tc-backend/**'
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tc-backend

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ou a versão do seu projeto

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Rodar Pylint
        run: |
          pylint .